# Generated by Django 3.2.4 on 2021-08-01 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_customuser_is_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.customuser')),
            ],
            options={
                'verbose_name': 'Stock Manager',
                'verbose_name_plural': ' Stock Managers',
            },
            bases=('user.customuser',),
        ),
        migrations.CreateModel(
            name='StockProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
            options={
                'verbose_name': ' Stock Manager Profile',
                'verbose_name_plural': ' Stock Manager Profiles',
            },
            bases=('user.profile',),
        ),
        migrations.CreateModel(
            name='StockFeedback',
            fields=[
                ('feedback_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.feedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
            options={
                'verbose_name': ' Stock Manager',
                'verbose_name_plural': ' Stock Manager Feedback',
            },
            bases=('user.feedback',),
        ),
    ]
