# Generated by Django 3.2.4 on 2021-07-20 09:52

import autoslug.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='product/default.jpg', upload_to='product/%y/%m')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=250)),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('is_archived', models.BooleanField(default=False, help_text='Means the oder has been cancelled.', verbose_name='Archived')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=250)),
                ('mpesa', models.CharField(help_text='Mpesa Code e.g MXFTR432R5', max_length=10)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('amount', models.FloatField(default=0.0)),
                ('confirmed', models.BooleanField(default=False, help_text='Means manager has confirmed payment')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='slug_name')),
                ('discount', models.FloatField(choices=[(0.05, '95 %'), (0.1, '90 %'), (0.15, '85 %'), (0.2, '80 %'), (0.25, '75 %'), (0.3, '70 %'), (0.35, '65 %'), (0.4, '60 %'), (0.45, '55 %'), (0.5, '50 %'), (0.55, '45 %'), (0.6, '40 %'), (0.65, '35 %'), (0.7, '30 %'), (0.75, '25 %'), (0.8, '20 %'), (0.85, '15 %'), (0.9, '10 %'), (0.95, '5 %'), (1.0, '0 %')], default=1.0)),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('image', models.ImageField(null=True, upload_to='product/images/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('is_discount', models.BooleanField(default=False, help_text='when active, discount will be applied', verbose_name='Discount')),
                ('is_active', models.BooleanField(default=False, help_text='Activated, allow to publish', verbose_name='Active')),
                ('is_archived', models.BooleanField(default=False, help_text='Activated, gets unpublished', verbose_name='Archived')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.BooleanField(default=False, help_text='means product is in cart')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
        ),
    ]
