# Generated by Django 3.2.4 on 2021-07-20 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0002_trainingapplication_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingpayment',
            name='trainee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainee.trainee'),
        ),
    ]
