# Generated by Django 3.2.4 on 2021-08-02 17:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0003_trainingpayment_trainee'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
