# Generated by Django 3.2.4 on 2021-08-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0004_training_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
