# Generated by Django 3.2.4 on 2021-07-20 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.customuser')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
            bases=('user.customuser',),
        ),
        migrations.CreateModel(
            name='ShipmentLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('price', models.FloatField(default=0.0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.profile')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.shipmentlocations')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shipment.agent')),
            ],
            options={
                'verbose_name': 'Agent Profile',
                'verbose_name_plural': 'Agents Profile',
            },
            bases=('user.profile',),
        ),
        migrations.CreateModel(
            name='AgentFeedback',
            fields=[
                ('feedback_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.feedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.agent')),
            ],
            options={
                'verbose_name': 'Agent Feedback',
                'verbose_name_plural': 'Agents Feedback',
            },
            bases=('user.feedback',),
        ),
    ]
