# Generated by Django 3.2.4 on 2021-07-20 09:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Appointment Date')),
                ('completed', models.BooleanField(default=False, help_text='Means customer was served')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='Apprenticeship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Appointment Date')),
                ('closed', models.BooleanField(default=False, verbose_name='closed')),
                ('is_active', models.BooleanField(default=False, help_text='Activated, means Apprenticeship will be published', verbose_name='Active')),
                ('is_archived', models.BooleanField(default=False, help_text='Archived, means Apprenticeship will be Unpublished', verbose_name='Archive')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='ApprenticeshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(help_text='Means Customer attended the program')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=False, help_text='Means Appointment has been booked', verbose_name='Appointment')),
                ('is_paid', models.BooleanField(default=False, help_text='Means Customer has paid', verbose_name='Paid')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpesa', models.CharField(help_text='Mpesa Code', max_length=10)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('amount', models.FloatField(default=0.0)),
                ('confirmed', models.BooleanField(default=False, help_text='Means manager has confirmed payment')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='SalonistService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, help_text='Activated, means Service will be published', verbose_name='Active')),
                ('is_archived', models.BooleanField(default=False, help_text='Archived, means Service will be Unpublished', verbose_name='Archive')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
            ],
        ),
    ]
