# Generated by Django 3.2.4 on 2021-07-20 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('salonist', '0001_initial'),
        ('customer', '0001_initial'),
        ('service', '0001_initial'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonistservice',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.manager'),
        ),
        migrations.AddField(
            model_name='salonistservice',
            name='salonist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salonist.salonist'),
        ),
        migrations.AddField(
            model_name='salonistservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salonist.service'),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.booking'),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='bookingpayment',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.finance'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salonist.service'),
        ),
        migrations.AddField(
            model_name='apprenticeshipapplication',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='apprenticeshipapplication',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.apprenticeship'),
        ),
        migrations.AddField(
            model_name='apprenticeshipapplication',
            name='salonist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salonist.salonist'),
        ),
        migrations.AddField(
            model_name='apprenticeship',
            name='salonist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salonist.salonist'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.booking'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='salonist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salonist.salonist'),
        ),
    ]
