# Generated by Django 3.2.4 on 2021-07-31 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='stop_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Appointment Stop Date Time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(help_text='Appointment Start Date Time'),
        ),
    ]
