# Generated by Django 3.2.4 on 2021-08-02 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('service', '0003_auto_20210731_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingpayment',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.finance'),
        ),
    ]
