# Generated by Django 3.2.4 on 2021-07-20 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salonist',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.customuser')),
            ],
            options={
                'verbose_name': 'Salonist',
                'verbose_name_plural': 'Salonist',
            },
            bases=('user.customuser',),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='service/default.jpg', upload_to='service/%y/%m')),
                ('price', models.FloatField()),
                ('is_active', models.BooleanField(default=False, help_text='Activated, means Service will be published', verbose_name='Active')),
                ('is_archived', models.BooleanField(default=False, help_text='Archived, means Service will be Unpublished', verbose_name='Archive')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='SalonistProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.profile')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salonist.service')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='salonist.salonist')),
            ],
            options={
                'verbose_name': 'Salonist Profile',
                'verbose_name_plural': 'Salonist Profile',
            },
            bases=('user.profile',),
        ),
        migrations.CreateModel(
            name='SalonistFeedback',
            fields=[
                ('feedback_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.feedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salonist.salonist')),
            ],
            options={
                'verbose_name': 'Salonist Feedback',
                'verbose_name_plural': 'Salonist Feedback',
            },
            bases=('user.feedback',),
        ),
    ]
