# Generated by Django 3.2.4 on 2021-07-20 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.customuser')),
            ],
            options={
                'verbose_name': ' Manager',
                'verbose_name_plural': ' Managers',
            },
            bases=('user.customuser',),
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manager.manager')),
            ],
            options={
                'verbose_name': ' Manager Profile',
                'verbose_name_plural': ' Managers Profile',
            },
            bases=('user.profile',),
        ),
        migrations.CreateModel(
            name='ManagerFeedback',
            fields=[
                ('feedback_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.feedback')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.manager')),
            ],
            options={
                'verbose_name': ' Manager',
                'verbose_name_plural': ' Manager Feedback',
            },
            bases=('user.feedback',),
        ),
    ]
